### PR TITLE
Only ask to run migrations on successful deploy

### PR DESCRIPTION
**Pull request by remiprev**
When we deploy new code, let’s make sure the deploy went OK before we ask if we want to run the migrations.

### CODE REVIEW

**Comment by charlesdemers** [comment]
Looks good to me :+1:

**Comment by pascalhamel** [comment]
LGTM :+1:

**Comment by remiprev** [comment]
@garno I’m gonna wait for your :+1: since you’re the official maintainer :smile:

**Comment by garno** [comment]
:+1:

**Comment by simonprev** [comment]
:+1:

**Pull request merged**
